services:
  sjur-app:
    build: .
    container_name: sjur-poc
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data            # <-- persistência do banco
      - ./logs:/app/logs            # (se desejar manter logs)
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
    restart: unless-stopped
