# .streamlit/config.toml
[server]
maxMessageSize = 1000  # Aumenta para 1000MB
fileWatcherType = "none"  # Melhora performance
enableCORS = false  # Desativa CORS para desenvolvimento
enableXsrfProtection = false  # Desativa proteção XSRF

[browser]
serverAddress = "localhost"
serverPort = 8501

# Configurações de execução
[runner]
magicEnabled = false  # Desativa magic commands para melhor performance

# Configurações do cliente
[client]
showErrorDetails = true  # Mostra detalhes de erros
